### ISSUE TITLE
Markymark fonts overwriting font from other libraries

### ISSUE THREAD

**Issue by lenarother** [moccu/django-markymark#19] opened 2018-08-23 11:55 UTC
Hallo,

the fonts in markymark are overwriting fonts in other libraries e.g. filer, and the fonts are not correctly shown. E.g. the image edit icon (fa-pencil): 

![screen shot 2018-08-23 at 13 53 38](https://user-images.githubusercontent.com/2233372/44523946-0f080580-a6dc-11e8-9b60-f8e2ec9c0471.png)

LG,
Sascha & Magda

**Comment by stephrdev** [comment] 2018-08-23 12:01
Looks like different versions of font awesome. You could try to disable the icon library of markymark and see if the filer icon font works too. (see https://django-markymark.readthedocs.io/en/stable/configuration.html#MARKYMARK_FONTAWESOME_CSS)

In the long run me might need to have configurable "icon-prefix" or something like that.

**Comment by deluge** [comment] 2018-08-24 10:56
Using the ``MARKYMARK_FONTAWESOME_CSS`` setting doesn´t work. I tried to use https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css and this is what it looks like:

![screen shot 2018-08-24 at 12 41 37](https://user-images.githubusercontent.com/847875/44580722-50131f00-a79b-11e8-8aef-b78dd0129ed1.png)

The problem is that the old version doesn´t contain the new classes/icon-fonts. The font of version 5.x is a free version and doesn´t include the old one.

I figured out, that filer uses ``fa-pencil`` and in fontawesome 5.x it was renamed to fa-pencil-alt. The pro version has more icons and contains fa-pencil. (see  [https://fontawesome.com/icons?d=gallery&q=pencil](https://fontawesome.com/icons?d=gallery&q=pencil)

**Comment by stephrdev** [comment] 2018-08-24 10:57
Have you tried to just disable the icon scss by setting it do None?

**Comment by deluge** [comment] 2018-08-24 10:59
I talked with @Schascha & @lenarother and it doesn´t work, too.

**Comment by deluge** [comment] 2018-08-24 11:05
One confusing point is, if I use markymark with default settings (fontawesome 5.x) and changing the ordering of the fields (first markymark then filer-field) all works fine.

![screen shot 2018-08-24 at 13 02 52](https://user-images.githubusercontent.com/847875/44581546-6b335e00-a79e-11e8-9c7b-814f208f5b5b.png)

**Comment by stephrdev** [comment] 2018-08-24 11:16
Looks like we need to add support for FontAwesome 4 again, to reduce conflicts with other libraries like django-filer.

To do so, we need to add another icon type to all toolbar items (see https://github.com/moccu/django-markymark/blob/master/markymark/static/markymark/js/markdown-editor.js#L1053, and all other buttons). The default icon library is set here: https://github.com/moccu/django-markymark/blob/master/markymark/static/markymark/js/markdown-editor.js#L1037

The "fa" icon library should remain as it is. We need to add "fa4". In addition, we allow adding a custom iconlibrary setting to the widgets by adding a data attribute here: https://github.com/moccu/django-markymark/blob/master/markymark/widgets.py#L17 - the content of that attribute should be a setting.

**Comment by stephrdev** [comment] 2018-09-11 09:06
Fixed in 2.1.0.

**Closed by stephrdev** 2018-09-11 09:06 UTC
